services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      POSTGRES_DB: game_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database
    hostname: database

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
      - database
    hostname: backend

  frontend:
    build:
      context: ./frontend
    restart: always
    hostname: frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - backend

volumes:
  db-data:

networks:
  database:
  backend:
