services:
  db:
    build:
      context: ./database
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      POSTGRES_DB: game_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database
    hostname: database

  db_management:
    image: ghcr.io/shyim/adminerevo:latest
    restart: always
    environment:
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DEFAULT_USER=${POSTGRES_USER}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - ADMINER_DEFAULT_PASSWORD=game_db
    hostname: dbmanagement
    networks:
      - frontend
      - database

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      API_KEY: ${API_KEY}
    networks:
      - frontend
      - database
    hostname: backend

  frontend:
    build:
      context: ./frontend
    restart: always
    hostname: frontend
    environment:
      API_KEY: ${API_KEY}
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - frontend

volumes:
  db-data:

networks:
  database:
  frontend:
