services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

      POSTGRES_DB: game_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database
    hostname: database
    
  backend:
    build:
      context: ./backend
    restart: always
    networks:
      - backend
      - database
    hostname: backend

  frontend:
    build:
      context: ./frontend
    restart: always
    hostname: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - backend

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker/makerspace-spinner-scoreboard_db-data

networks:
  database:
  backend:
